   long int runNo;
   long int eventNo;
   double weight;
   double sqrts;
   double abst;
   double massEtaPi0;
   double massEta;
   double massPi0;
   double phiR;
   double thetaGJ;
   double phiGJ;
   double thetaEta;
   double phiEta;
   double thetaPi0;
   double phiPi0;
   int momentsGJ;
   int momentsEta;
   int momentsPi0;
   double YmomGJ[169];
   double YmomEta[169];
   double YmomPi0[169];
   double model1moment[169];
